services:
  db:
    image: postgres:16.3
    container_name: webback-chat-postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5434:5432" 
    volumes:
      - chat_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - chat-network

  chat-service:
    container_name: webback-chat-service
    ports:
      - "127.0.0.1:3003:3003"
    environment:
      - DB_ADDR=${DB_ADDR}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - chat-network
      - webback-net
    restart: on-failure

volumes:
  chat_data:

networks:
  chat-network:
    driver: bridge
  webback-net:
    external: true
